# Generated by Django 5.1.7 on 2025-08-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_merge_20250722_1043'),
        ('reservas', '0007_merge_20250723_2054'),
    ]

    operations = [
    ]
