# Generated by Django 5.2.3 on 2025-08-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_merge_20250804_2116'),
        ('reservas', '0008_merge_20250808_0047'),
    ]

    operations = [
    ]
